Cleanup SDMetrics to only accept SDV 1.0 metadata format
sdv-dev/SDMetrics pull request #334
Opened 2023-04-07 21:00 UTC by amontanez24

resolves #331

2023-04-11 22:16 UTC, frances-h requested changes
I think two test files got missed: [multi-table quality report](https://github.com/sdv-dev/SDMetrics/blob/issue-331-remove-old-metadata/tests/unit/reports/multi_table/test_multi_table_quality_report.py) and [multi-table diagnostic report](https://github.com/sdv-dev/SDMetrics/blob/issue-331-remove-old-metadata/tests/unit/reports/multi_table/test_multi_table_quality_report.py), but otherwise it's looking really good!

2023-04-12 14:16 UTC, frances-h approved these changes

2023-04-12 17:22 UTC, pvk-developer approved these changes
LGTM!
I left a comment if its easy to address feel free to add it 👍🏻

2023-04-12 17:22 UTC, pvk-developer commented on sdmetrics/demos/multi_table/metadata.json
Could we use `indent=4` on all our `.json` files in the demos ?

2023-04-12 20:23 UTC, merged