Create Parent - Child relationship property class
sdv-dev/SDMetrics pull request #369
Opened 2023-06-20 16:19 UTC by pvk-developer

Resolves #359

2023-06-26 16:10 UTC, frances-h approved these changes

2023-06-26 22:05 UTC, amontanez24 requested changes

2023-06-26 22:05 UTC, amontanez24 commented on sdmetrics/reports/multi_table/_properties/relationship.py
> +class CardinalityShapeSimilarityProperty(BaseMultiTableProperty):
We can just call it `Cardinality`. Can we also rename the file to match?

2023-06-26 22:05 UTC, amontanez24 commented on tests/unit/reports/multi_table/_properties/test_relationship.py
> +        expected_score_breakdwons = {
typo: breakdwons

2023-06-26 22:05 UTC, amontanez24 commented on sdmetrics/reports/multi_table/_properties/relationship.py
> +                pass
I think in the other metrics we are appending the error message to a new column with the header `Error`. We should do the same. That is the old behavior too I believe

2023-06-28 19:01 UTC, amontanez24 approved these changes
LGTM! Thanks for the changes :shipit:

2023-06-30 10:30 UTC, merged