Update codecov and add flag for integration tests
sdv-dev/SDMetrics pull request #667
Opened 2024-11-15 18:27 UTC by pvk-developer

Resolves #644 
CU-86b2mqara

2024-11-15 18:27 UTC, sdv-team commented
Task linked: [CU-86b2mqara SDMetrics - Update codecov and add flag for integration tests #644](https://app.clickup.com/t/86b2mqara)

2024-11-18 16:08 UTC, gsheni requested changes

2024-11-18 16:08 UTC, gsheni commented on .github/workflows/integration.yml
> +        file: './integration_cov.xml'
```suggestion
        fail_ci_if_error: true
        files: ${{ github.workspace }}/integration_cov.xml
```

2024-11-18 16:08 UTC, gsheni commented on .github/workflows/unit.yml
> +        file: './unit_cov.xml'
```suggestion
        fail_ci_if_error: true
        files: ${{ github.workspace }}/unit_cov.xml
```

2024-11-18 16:17 UTC, gsheni approved these changes

2024-11-18 16:23 UTC, gsheni approved these changes

2024-11-19 16:56 UTC, amontanez24 approved these changes

2024-11-19 18:06 UTC, gsheni approved these changes

2024-11-21 18:29 UTC, merged